/**
 * Trace the reference's white ink into a filled SVG outline.
 * Run `pnpm wordmark:build [image]`. Pen trajectories live in wordmark-reveal:
 * a bitmap skeleton cannot recover the order of crossing strokes.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'
import { buildReveal } from './wordmark-reveal'

type Point = [number, number]

function simplify(points: Point[], tolerance: number): Point[] {
  if (points.length < 3) return points
  const [ax, ay] = points[0]
  const [bx, by] = points[points.length - 1]
  const length = Math.hypot(bx - ax, by - ay) || 1
  let farthest = 0
  let distance = 0
  for (let i = 1; i < points.length - 1; i++) {
    const [x, y] = points[i]
    const d = Math.abs((x - ax) * (by - ay) - (y - ay) * (bx - ax)) / length
    if (d > distance) {
      farthest = i
      distance = d
    }
  }
  if (distance <= tolerance) return [points[0], points[points.length - 1]]
  return [
    ...simplify(points.slice(0, farthest + 1), tolerance).slice(0, -1),
    ...simplify(points.slice(farthest), tolerance)
  ]
}

function area(ring: Point[]) {
  return ring.reduce((sum, [x, y], i) => {
    const next = ring[(i + 1) % ring.length]
    return sum + x * next[1] - next[0] * y
  }, 0) / 2
}

async function main() {
  const source = process.argv[2] || 'scripts/assets/razzh-reference.jpg'
  // Keep the coordinate system shared with the hand-drawn reveal paths.
  const size = 564
  const scale = 3
  const { data, info } = await sharp(source)
    .resize(size * scale, size * scale, { fit: 'fill' })
    .greyscale()
    .blur(0.8)
    .raw()
    .toBuffer({ resolveWithObject: true })
  const { width, height } = info
  const ink = (x: number, y: number) => x >= 0 && y >= 0 && x < width && y < height && data[y * width + x] > 128
  const edges = new Map<string, Point[]>()
  const edge = (x: number, y: number, to: Point) => {
    const key = `${x},${y}`
    edges.set(key, [...(edges.get(key) || []), to])
  }
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (!ink(x, y)) continue
      if (!ink(x, y - 1)) edge(x, y, [x + 1, y])
      if (!ink(x + 1, y)) edge(x + 1, y, [x + 1, y + 1])
      if (!ink(x, y + 1)) edge(x + 1, y + 1, [x, y + 1])
      if (!ink(x - 1, y)) edge(x, y + 1, [x, y])
    }
  }

  const rings: Point[][] = []
  while (edges.size) {
    const start = edges.keys().next().value as string
    let cursor = start
    const ring: Point[] = []
    do {
      const destinations = edges.get(cursor)
      if (!destinations?.length) throw new Error('Open outline in reference image')
      ring.push(cursor.split(',').map(Number) as Point)
      const next = destinations.pop()!
      if (!destinations.length) edges.delete(cursor)
      cursor = next.join(',')
    } while (cursor !== start)
    if (Math.abs(area(ring)) < 40) continue
    // Split the closed ring at its opposite point before simplifying each half.
    let split = 0
    let distance = 0
    ring.forEach(([x, y], i) => {
      const d = Math.hypot(x - ring[0][0], y - ring[0][1])
      if (d > distance) {
        split = i
        distance = d
      }
    })
    rings.push([
      ...simplify(ring.slice(0, split + 1), 1.2).slice(0, -1),
      ...simplify([...ring.slice(split), ring[0]], 1.2).slice(0, -1)
    ])
  }
  if (!rings.length) throw new Error('No white ink found in reference image')
  const number = (n: number) => +(n / scale).toFixed(2)
  const outline = rings.map(ring => `M${ring.map(([x, y]) => `${number(x)} ${number(y)}`).join('L')}Z`).join('')
  const output = path.resolve('components/layout/razzh-wordmark-paths.ts')
  const { slices, frames } = await buildReveal(outline)
  await fs.writeFile(output, `// Generated by pnpm wordmark:build from scripts/assets/razzh-reference.jpg.\n// Keep the counters transparent with fillRule="evenodd".\nexport const RAZZH_OUTLINE = '${outline}'\n\n// Connected reveal bands in writing order.\nexport const RAZZH_REVEAL_STEPS = ${frames}\nexport const RAZZH_REVEAL = ${JSON.stringify(slices)}\n`)
  console.log(`Traced ${rings.length} contours (${outline.length} characters) -> ${output}`)
}

main().catch(error => {
  console.error(error)
  process.exitCode = 1
})
